#!/usr/bin/perl

for ("00", "01", "02", "03",
     "10", "11", "12", "13",
     "20", "21", "22", "23",
     "30", "31", "32", "33") {
  print qx(fusermount -u $_);
  print qx(mkdir -p $_);
  print qx(sshfs -o reconnect,sshfs_sync,no_readahead,cache=no root\@$_.cf:/ $_);
}
